language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=imgprocalgs --cov=tests --cov=docs/src --cov-report=term-missing tests

after_script:
  - bash <(curl -s https://codecov.io/bash)
